# Generated by Django 3.2.7 on 2021-09-06 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.IntegerField(max_length=20, unique=True, verbose_name='Identificación')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('phone', models.CharField(max_length=15, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Correo Electronico')),
            ],
        ),
    ]
