# Generated by Django 3.2.7 on 2021-09-06 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='document',
            field=models.BigIntegerField(max_length=15, unique=True, verbose_name='Identificación'),
        ),
    ]
